plugins {
    id 'java'
    id 'application'
}

group = 'ru.mcs'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    implementation 'org.linguafranca.pwdb:KeePassJava2:2.2.4'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
}

application {
    mainClass = 'ru.mcs.DockerSecretLauncher'
}

tasks.register('fatJar', Jar) {
    archiveClassifier = 'all'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': 'ru.mcs.DockerSecretLauncher'
    }
    from sourceSets.main.output
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/MANIFEST.MF'
}

tasks.named('build') {
    dependsOn tasks.named('fatJar')
}